name: Spring Boot Tests

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '20'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run Spring Boot Tests
        run: ./gradlew test
